### PR TITLE
Update go.mod with newer pretty version required by ebpf

### PR DESCRIPTION
**Pull request by blanquicet**
This PR updates pretty module to version 0.2.1 because it is required by ebpf version 0.4.0 which was introduced in 320f8f01
(Implement support for Node Resource Interface).

Current compilation error:
```
$ make gadget-container-local
...
mkdir -p bin
GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build \
	-o bin/ocihookgadget \
	./hooks/oci/main.go
go: github.com/kr/pretty@v0.2.1: missing go.sum entry; to add it:
	go mod download github.com/kr/pretty
make[1]: *** [Makefile:29: ocihookgadget] Error 1
```

After debugging, it was possible to find that ebpf v0.4.0 is asking for pretty v0.2.1:

```
$ make gadget-container-local
...
mkdir -p bin
GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build \
	-o bin/ocihookgadget \
	./hooks/oci/main.go
go: github.com/cilium/ebpf@v0.4.0 requires
	github.com/frankban/quicktest@v1.11.3 requires
	github.com/kr/pretty@v0.2.1: missing go.sum entry; to add it:
	go mod download github.com/kr/pretty
```

### CODE REVIEW

**Review by mauriciovasquezbernal — APPROVED** [review]
LGTM thanks.

PD: I don't know why it wasn't caught by the CI. Perhaps because the compilation inside the container (`make gadget-container`) was working fine?
